name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port:  ${{ secrets.SERVER_PORT }}
        script: |
          cd /var/www/web-sam
          
          git pull origin main
          
          export COMPOSER_ALLOW_SUPERUSER=1
          composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
          
          php artisan optimize:clear
          
          sudo systemctl restart php8.2-fpm
          sudo systemctl restart nginx
